#!/bin/bash
#SBATCH --job-name=baseline_cv
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4     
#SBATCH --time=04:00:00    
#SBATCH --output=VAULT/BASELINE/baseline_Uncon.out  
#SBATCH --error=VAULT/BASELINE/baseline_Uncon.err

echo "--- Starting SLURM Job ---"
echo "Allocated Node: $SLURMD_NODENAME"
echo "Job ID: $SLURM_JOB_ID"

module load 2023
module load Python/3.11.3-GCCcore-12.3.0

source $SLURM_SUBMIT_DIR/thesis_env/bin/activate

cd $SLURM_SUBMIT_DIR

mkdir -p VAULT/BASELINE/

BASE_PATH="VAULT/BASELINE/baseline_Uncon"
WEIGHT_FILE="${BASE_PATH}.pth"

srun python main.py \
    --epochs 20 \
    --batch_size 32 \
    --lr 1e-4 \
    --num_workers 4 \
    --data_dir "/scratch-shared/$USER/data/raw/" \
    --csv_path "/scratch-shared/$USER/data/raw/master_metadata_split.csv" \
    --save_path "$WEIGHT_FILE"

if [ $? -eq 0 ]; then
    echo "Training successful. Initiating test set evaluation..."
    srun python evaluate.py --weights $WEIGHT_FILE
else
    echo "Training crashed. Skipping evaluation."
fi

echo "SLURM job complete"