#!/bin/bash
#SBATCH --job-name=kcn_exp
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4     
#SBATCH --time=12:00:00       # Increased time to allow 3 sequential runs
#SBATCH --output=VAULT/KCN/%x_%j.out  
#SBATCH --error=VAULT/KCN/%x_%j.err

echo "--- Starting KCN Hyperparameter War ---"
echo "Allocated Node: $SLURMD_NODENAME"

module load 2023
module load Python/3.11.3-GCCcore-12.3.0
source $SLURM_SUBMIT_DIR/thesis_env/bin/activate
cd $SLURM_SUBMIT_DIR

mkdir -p VAULT/KCN

DATA_DIR="/scratch-shared/$USER/data/raw/"
CSV_PATH="/scratch-shared/$USER/data/raw/master_metadata_split.csv"
EPOCHS=25

# echo "=========================================="
# echo "EXPERIMENT 1: Heavy Spline Penalty"
# echo "=========================================="
# EXP1_BASE="VAULT/KCN/Paths/kcn_heavy_spline"

# srun python main_kcn.py \
#     --epochs $EPOCHS \
#     --batch_size 32 \
#     --lr 1e-4 \
#     --reg_weight 1e-3 \
#     --weight_decay 1e-3 \
#     --dropout 0.5 \
#     --data_dir "$DATA_DIR" \
#     --csv_path "$CSV_PATH" \
#     --save_path "${EXP1_BASE}.pth"

# if [ $? -eq 0 ]; then
#     echo "Exp 1 Training successful. Evaluating Dual Checkpoints..."
#     srun python evaluate_kcn.py --weights "${EXP1_BASE}_best_loss.pth"
#     srun python evaluate_kcn.py --weights "${EXP1_BASE}_best_f1.pth"
# fi

echo "=========================================="
echo "EXPERIMENT 2: Extreme Spline Penalty"
echo "=========================================="
EXP2_BASE="VAULT/KCN/Paths/kcn_extreme_spline"

srun python main_kcn.py \
    --epochs $EPOCHS \
    --batch_size 32 \
    --lr 1e-4 \
    --reg_weight 5e-3 \
    --weight_decay 1e-3 \
    --dropout 0.5 \
    --data_dir "$DATA_DIR" \
    --csv_path "$CSV_PATH" \
    --save_path "${EXP2_BASE}.pth"

# if [ $? -eq 0 ]; then
#     echo "Exp 2 Training successful. Evaluating Dual Checkpoints..."
#     srun python evaluate_kcn.py --weights "${EXP2_BASE}_best_loss.pth"
#     srun python evaluate_kcn.py --weights "${EXP2_BASE}_best_f1.pth"
# fi

echo "=========================================="
echo "EXPERIMENT 3: Weight Decay Chokehold"
echo "=========================================="
EXP3_BASE="VAULT/KCN/Paths//kcn_decay_choke"

srun python main_kcn.py \
    --epochs $EPOCHS \
    --batch_size 32 \
    --lr 1e-4 \
    --reg_weight 1e-3 \
    --weight_decay 1e-2 \
    --dropout 0.6 \
    --data_dir "$DATA_DIR" \
    --csv_path "$CSV_PATH" \
    --save_path "${EXP3_BASE}.pth"

# if [ $? -eq 0 ]; then
#     echo "Exp 3 Training successful. Evaluating Dual Checkpoints..."
#     srun python evaluate_kcn.py --weights "${EXP3_BASE}_best_loss.pth"
#     srun python evaluate_kcn.py --weights "${EXP3_BASE}_best_f1.pth"
# fi

echo "All experiments complete."